'use strict';

angular.module('recuserstudyApp')
  .service('Movies', function () {

    var self = this;

    this.all = {
      "0": {
        name: "Django Unchained",
        year: "2012",
        datePublished: "25 December 2012",
        country: "USA",
        length: 165,
        category: "Western",
        director: "Quentin Tarantino",
        actors: "Jamie Foxx, Christoph Waltz, Leonardo DiCaprio",
        description: "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.",
        image: "http://ia.media-imdb.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_SX214_AL_.jpg",
        recommend: [0,1,2,3]
      },
      "1": {
        name: "Gravity",
        year: "2013",
        datePublished: "4 October 2013",
        country: "USA",
        length: 91,
        category: "Sci-Fi, Thriller",
        director: "Alfonso Cuarón",
        actors: "Sandra Bullock, George Clooney, Ed Harris",
        description: "A medical engineer and an astronaut work together to survive after a catastrophe destroys their shuttle and leaves them adrift in orbit.",
        image: "http://ia.media-imdb.com/images/M/MV5BNjE5MzYwMzYxMF5BMl5BanBnXkFtZTcwOTk4MTk0OQ@@._V1_SY317_CR0,0,214,317_AL_.jpg",
        recommend: [4,5,6,7]
      },
      "2": {
        name: "Black Swan",
        year: "2010",
        datePublished: "17 December",
        country: "USA",
        length: 108,
        category: "Drama, Mystery, Thriller",
        director: "Darren Aronofsky",
        actors: "Natalie Portman, Mila Kunis, Vincent Cassel",
        description: 'A ballet dancer wins the lead in "Swan Lake" and is perfect for the role of the delicate White Swan - Princess Odette - but slowly loses her mind as she becomes more and more like Odile, the Black Swan.',
        image: "http://ia.media-imdb.com/images/M/MV5BNzY2NzI4OTE5MF5BMl5BanBnXkFtZTcwMjMyNDY4Mw@@._V1_SX214_AL_.jpg",
        recommend: [4,5,8,9]
      },
      "3": {
        name: "Mad Max: Fury Road",
        year: "2015",
        datePublished: "15 May 2015",
        country: "USA",
        length: 120,
        category: "Action, Adventure, Sci-Fi",
        director: "George Miller",
        actors: "Tom Hardy, Charlize Theron, Nicholas Hoult",
        description: "In a stark desert landscape where humanity is broken, two rebels just might be able to restore order: Max, a man of action and of few words, and Furiosa, a woman of action who is looking to make it back to her childhood homeland.",
        image: "http://ia.media-imdb.com/images/M/MV5BMTUyMTE0ODcxNF5BMl5BanBnXkFtZTgwODE4NDQzNTE@._V1_SY317_CR2,0,214,317_AL_.jpg",
        recommend: [10,11,12,13]
      },
      "4": {
        name: "Toy Story 3",
        year: "2010",
        datePublished: "18 June 2010",
        country: "USA",
        length: 103,
        category: "Animation, Adventure, Comedy ",
        director: "Lee Unkrich",
        actors: "Tom Hanks, Tim Allen, Joan Cusack",
        description: "The toys are mistakenly delivered to a day-care center instead of the attic right before Andy leaves for college, and it's up to Woody to convince the other toys that they weren't abandoned and to return home.",
        image: "http://ia.media-imdb.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SY317_CR5,0,214,317_AL_.jpg",
        recommend: [14,15,16,17]
      },
      "5": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: "",
        recommend: [20,21,22,23]
      },
      "6": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: "",
        recommend: [24,25,26,27]
      },
      "7": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: "",
        recommend: [28,29,30,31]
      },
      "8": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: "",
        recommend: [32,33,34,35]
      },
      "9": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: "",
        recommend: [36,37,38,39]
      },
      "10": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: "",
        recommend: [40,41,42,43]
      },
      "11": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: "",
        recommend: [44,45,46,47]
      },
      "12": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: "",
        recommend: [48,49,50,51]
      },
      "13": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: "",
        recommend: [52,53,54,55]
      },
      "14": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: "",
        recommend: [56,57,58,59]
      },
      "15": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: "",
        recommend: [60,61,62,63]
      },
      "16": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: "",
        recommend: [64,65,66,67]
      },
      "17": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: "",
        recommend: [68,69,70,71]
      },
      "18": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: "",
        recommend: [72,73,74,75]
      },
      "19": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: "",
        recommend: [76,77,78,79]
      },
      "20": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: "",
        recommend: [80,81,82,83]
      },
      "21": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: "",
        recommend: [84,85,86,87]
      },
      "22": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: "",
        recommend: [88,89,90,91]
      },
      "23": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: "",
        recommend: [92,93,94,95]
      },
      "24": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: "",
        recommend: [96,97,98,99]
      }
    };

    this.recommendations = {
      "0": {
        name: "Inglourious Basterds",
        year: "2009",
        datePublished: "21 August 2009",
        country: "USA",
        length: 153,
        category: "Adventure, Drama, War ",
        director: "Quentin Tarantino, Eli Roth (uncredited)",
        actors: "Brad Pitt, Diane Kruger, Eli Roth",
        description: "In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans for the same.",
        image: "http://ia.media-imdb.com/images/M/MV5BMjIzMDI4MTUzOV5BMl5BanBnXkFtZTcwNDY3NjA3Mg@@._V1_SY317_CR0,0,214,317_AL_.jpg"
      },
      "1": {
        name: "The Wolf of Wall Street",
        year: "2013",
        datePublished: "25 December 2013",
        country: "USA",
        length: 180,
        category: "Biography, Comedy, Crime",
        director: "Martin Scorsese",
        actors: "Leonardo DiCaprio, Jonah Hill, Margot Robbie",
        description: "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.",
        image: "http://ia.media-imdb.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_SX214_AL_.jpg"
      },
      "2": {
        name: "Fight Club",
        year: "1999",
        datePublished: "15 October 1999",
        country: "USA",
        length: 139,
        category: "Biography, Comedy, Crime",
        director: "David Fincher",
        actors: "Brad Pitt, Edward Norton, Helena Bonham Carter",
        description: "An insomniac office worker looking for a way to change his life crosses paths with a devil-may-care soap maker and they form an underground fight club that evolves into something much, much more...",
        image: "http://ia.media-imdb.com/images/M/MV5BMjIwNTYzMzE1M15BMl5BanBnXkFtZTcwOTE5Mzg3OA@@._V1_SX214_AL_.jpg"
      },
      "3": {
        name: "Inception",
        year: "2010",
        datePublished: "16 July 2010",
        country: "USA",
        length: 148,
        category: "Action, Mystery, Sci-Fi",
        director: "Christopher Nolan",
        actors: "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page",
        description: "A thief who steals corporate secrets through use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
        image: "http://ia.media-imdb.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX214_AL_.jpg"
      },
      "4": {
        name: "Life of Pi",
        year: "2012",
        datePublished: "21 November 2012",
        country: "USA",
        length: 127,
        category: "Adventure, Drama",
        director: "Ang Lee",
        actors: "Suraj Sharma, Irrfan Khan, Adil Hussain",
        description: "A young man who survives a disaster at sea is hurtled into an epic journey of adventure and discovery. While cast away, he forms an unexpected connection with another survivor: a fearsome Bengal tiger.",
        image: "http://ia.media-imdb.com/images/M/MV5BNTg2OTY2ODg5OF5BMl5BanBnXkFtZTcwODM5MTYxOA@@._V1_SX214_AL_.jpg"
      },
      "5": {
        name: "The Social Network",
        year: "2010",
        datePublished: "1 October 2010",
        country: "USA",
        length: 120,
        category: "Biography, Drama",
        director: "David Fincher",
        actors: "Jesse Eisenberg, Andrew Garfield, Justin Timberlake",
        description: "Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, but is later sued by two brothers who claimed he stole their idea, and the cofounder who was later squeezed out of the business.",
        image: "http://ia.media-imdb.com/images/M/MV5BMTM2ODk0NDAwMF5BMl5BanBnXkFtZTcwNTM1MDc2Mw@@._V1_SX214_AL_.jpg"
      },
      "6": {
        name: "Argo",
        year: "2012",
        datePublished: "12 October 2012",
        country: "USA",
        length: 120,
        category: "Drama, History, Thriller",
        director: "Ben Affleck",
        actors: "Ben Affleck, Bryan Cranston, John Goodman",
        description: "Acting under the cover of a Hollywood producer scouting a location for a science fiction film, a CIA agent launches a dangerous operation to rescue six Americans in Tehran during the U.S. hostage crisis in Iran in 1980.",
        image: "http://ia.media-imdb.com/images/M/MV5BMTc3MjI0MjM0NF5BMl5BanBnXkFtZTcwMTYxMTQ1OA@@._V1_SY317_CR0,0,214,317_AL_.jpg"
      },
      "7": {
        name: "Dallas Buyers Club",
        year: "2013",
        datePublished: "22 November 2013",
        country: "USA",
        length: 117,
        category: "Biography, Drama",
        director: "Jean-Marc Vallée",
        actors: "Matthew McConaughey, Jennifer Garner, Jared Leto",
        description: "In 1985 Dallas, electrician and hustler Ron Woodroof works around the system to help AIDS patients get the medication they need after he is himself diagnosed with the disease.",
        image: "http://ia.media-imdb.com/images/M/MV5BMTYwMTA4MzgyNF5BMl5BanBnXkFtZTgwMjEyMjE0MDE@._V1_SX214_AL_.jpg"
      },
      "8": {
        name: "Silver Linings Playbook",
        year: "2012",
        datePublished: "25 December 2012",
        country: "USA",
        length: 122,
        category: "Comedy, Drama, Romance",
        director: "David O. Russell",
        actors: "Bradley Cooper, Jennifer Lawrence, Robert De Niro",
        description: "After a stint in a mental institution, former teacher Pat Solitano moves back in with his parents and tries to reconcile with his ex-wife. Things get more challenging when Pat meets Tiffany, a mysterious girl with problems of her own.",
        image: "http://ia.media-imdb.com/images/M/MV5BMTM2MTI5NzA3MF5BMl5BanBnXkFtZTcwODExNTc0OA@@._V1_SX214_AL_.jpg"
      },
      "9": {
        name: "The Curious Case of Benjamin Button",
        year: "2008",
        datePublished: "25 December 2008",
        country: "USA",
        length: 166,
        category: "Drama, Fantasy, Romance",
        director: "David Fincher",
        actors: "Brad Pitt, Cate Blanchett, Tilda Swinton",
        description: "Tells the story of Benjamin Button, a man who starts aging backwards with bizarre consequences.",
        image: "http://ia.media-imdb.com/images/M/MV5BNjQ0NTY2ODY2M15BMl5BanBnXkFtZTgwMjE4MzkxMDE@._V1_SY317_CR0,0,214,317_AL_.jpg"
      },
      "10": {
        name: "Avengers: Age of Ultron",
        year: "2015",
        datePublished: "1 May 2015",
        country: "USA",
        length: 141,
        category: "Action, Adventure, Sci-Fi",
        director: "Joss Whedon",
        actors: "Robert Downey Jr., Chris Evans, Mark Ruffalo",
        description: "When Tony Stark and Bruce Banner try to jump-start a dormant peacekeeping program called Ultron, things go horribly wrong and it's up to Earth's Mightiest Heroes to stop the villainous Ultron from enacting his terrible plans.",
        image: "http://ia.media-imdb.com/images/M/MV5BMTU4MDU3NDQ5Ml5BMl5BanBnXkFtZTgwOTU5MDUxNTE@._V1_SY317_CR1,0,214,317_AL_.jpg"
      },
      "11": {
        name: "Mad Max Beyond Thunderdome",
        year: "1985",
        datePublished: "10 July 1985",
        country: "USA",
        length: 107,
        category: "Action, Adventure, Sci-Fi ",
        director: "George Miller, George Ogilvie",
        actors: "Mel Gibson, Tina Turner, Bruce Spence",
        description: "A former Australian policeman is rescued by a tribe of children when he is banished from a desert town and sent into the desert to die by the desert town's evil queen.",
        image: "http://ia.media-imdb.com/images/M/MV5BMTk0MDQ5NTYxNV5BMl5BanBnXkFtZTcwNTA0ODYyMQ@@._V1_SY317_CR11,0,214,317_AL_.jpg"
      },
      "12": {
        name: "Mad Max",
        year: "1979",
        datePublished: "12 April 1979",
        country: "Australia",
        length: 88,
        category: "Action, Adventure, Sci-Fi ",
        director: "George Miller",
        actors: "Mel Gibson, Joanne Samuel, Hugh Keays-Byrne",
        description: "In a self-destructing world, a vengeful Australian policeman sets out to stop a violent motorcycle gang.",
        image: "http://ia.media-imdb.com/images/M/MV5BMTM4Mjg5ODEzMV5BMl5BanBnXkFtZTcwMDc3NDk0NA@@._V1_SX214_AL_.jpg"
      },
      "13": {
        name: "Tomorrowland",
        year: "2015",
        datePublished: "22 May 2015",
        country: "USA",
        length: 130,
        category: "Action, Adventure, Mystery ",
        director: "Brad Bird",
        actors: "George Clooney, Britt Robertson, Hugh Laurie",
        description: "Bound by a shared destiny, a teen bursting with scientific curiosity and a former boy-genius inventor embark on a mission to unearth the secrets of a place somewhere in time and space that exists in their collective memory.",
        image: "http://ia.media-imdb.com/images/M/MV5BMTQ4OTgzNTkwNF5BMl5BanBnXkFtZTgwMzI3MDE3NDE@._V1_SX214_AL_.jpg"
      },
      "14": {
        name: "Up",
        year: "2009",
        datePublished: "29 May 2009",
        country: "USA",
        length: 96,
        category: "Animation, Adventure, Comedy",
        director: "Pete Docter, Bob Peterson",
        actors: "Edward Asner, Jordan Nagai, John Ratzenberger",
        description: "To avoid being taken away to a nursing home, an old widower tries to fly his home to Paradise Falls, South America, along with a boy scout who accidentally lifted off with him.",
        image: "http://ia.media-imdb.com/images/M/MV5BMTk3NDE2NzI4NF5BMl5BanBnXkFtZTgwNzE1MzEyMTE@._V1_SX214_AL_.jpg"
      },
      "15": {
        name: "The Lion King",
        year: "1994",
        datePublished: "24 June 1994",
        country: "USA",
        length: 89,
        category: "Animation, Adventure, Drama",
        director: "Roger Allers, Rob Minkoff",
        actors: "Matthew Broderick, Jeremy Irons, James Earl Jones",
        description: "Tricked into thinking that he caused the death of his father, a lion cub flees and abandons his destiny as the future king.",
        image: "http://ia.media-imdb.com/images/M/MV5BMjEyMzgwNTUzMl5BMl5BanBnXkFtZTcwNTMxMzM3Ng@@._V1_SY317_CR15,0,214,317_AL_.jpg"
      },
      "16": {
        name: "Monsters, Inc.",
        year: "2001",
        datePublished: "2 November 2001",
        country: "USA",
        length: 92,
        category: "Animation, Adventure, Comedy ",
        director: "Pete Docter, David Silverman",
        actors: "Billy Crystal, John Goodman, Mary Gibbs",
        description: "Monsters generate their city's power by scaring children, but they are terribly afraid themselves of being contaminated by children, so when one enters Monstropolis, top scarer Sulley finds his world disrupted.",
        image: "http://ia.media-imdb.com/images/M/MV5BMTY1NTI0ODUyOF5BMl5BanBnXkFtZTgwNTEyNjQ0MDE@._V1_SX214_AL_.jpg"
      },
      "17": {
        name: "Finding Nemo",
        year: "2003",
        datePublished: "30 May 2003",
        country: "USA",
        length: 100,
        category: "Animation, Adventure, Comedy",
        director: "Andrew Stanton, Lee Unkrich",
        actors: "Albert Brooks, Ellen DeGeneres, Alexander Gould",
        description: "After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.",
        image: "http://ia.media-imdb.com/images/M/MV5BMTY1MTg1NDAxOV5BMl5BanBnXkFtZTcwMjg1MDI5Nw@@._V1_SY317_CR0,0,214,317_AL_.jpg"
      },
      "18": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "19": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "20": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "21": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "22": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "23": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "24": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "25": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "26": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "27": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "28": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "29": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "30": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "31": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "32": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "33": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "34": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "35": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "36": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "37": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "38": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "39": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "40": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "41": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "42": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "43": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "44": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "45": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "46": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "47": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "48": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "49": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "50": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "51": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "52": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "53": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "54": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "55": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "56": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "57": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "58": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "59": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "60": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "61": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "62": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "63": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "64": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "65": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "66": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "67": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "68": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "69": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "70": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "71": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "72": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "73": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "74": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "75": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "76": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "77": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "78": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "79": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "80": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "81": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "82": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "83": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "84": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "85": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "86": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "87": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "88": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "89": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "90": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "91": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "92": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "93": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "94": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "95": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "96": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "97": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "98": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      },
      "99": {
        name: "",
        year: "",
        datePublished: "",
        country: "USA",
        length: ,
        category: "",
        director: "",
        actors: "",
        description: "",
        image: ""
      }
    };

    this.user = [];

    this.withImages = null;

    this.alreadyDecided = false;

    this.completed = 0;
  });

