'use strict';

angular.module('recuserstudyApp')
  .service('Movies', function () {

    var self = this;

    this.all = {
      "0": {
        name: "Django Unchained",
        year: "2012",
        datePublished: "25 December 2012",
        country: "USA",
        length: 165,
        category: "Western",
        director: "Quentin Tarantino",
        actors: "Jamie Foxx, Christoph Waltz, Leonardo DiCaprio",
        description: "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.",
        image: "assets/images/all/1.jpg",
        recommend: [0,1,2,3]
      },
      "1": {
        name: "Gravity",
        year: "2013",
        datePublished: "4 October 2013",
        country: "USA",
        length: 91,
        category: "Sci-Fi, Thriller",
        director: "Alfonso CuarÃ³n",
        actors: "Sandra Bullock, George Clooney, Ed Harris",
        description: "A medical engineer and an astronaut work together to survive after a catastrophe destroys their shuttle and leaves them adrift in orbit.",
        image: "assets/images/all/2.jpg",
        recommend: [4,5,6,7]
      },
      "2": {
        name: "Black Swan",
        year: "2010",
        datePublished: "17 December",
        country: "USA",
        length: 108,
        category: "Drama, Mystery, Thriller",
        director: "Darren Aronofsky",
        actors: "Natalie Portman, Mila Kunis, Vincent Cassel",
        description: 'A ballet dancer wins the lead in "Swan Lake" and is perfect for the role of the delicate White Swan - Princess Odette - but slowly loses her mind as she becomes more and more like Odile, the Black Swan.',
        image: "assets/images/all/3.jpg",
        recommend: [4,5,8,9]
      },
      "3": {
        name: "Mad Max: Fury Road",
        year: "2015",
        datePublished: "15 May 2015",
        country: "USA",
        length: 120,
        category: "Action, Adventure, Sci-Fi",
        director: "George Miller",
        actors: "Tom Hardy, Charlize Theron, Nicholas Hoult",
        description: "In a stark desert landscape where humanity is broken, two rebels just might be able to restore order: Max, a man of action and of few words, and Furiosa, a woman of action who is looking to make it back to her childhood homeland.",
        image: "assets/images/all/4.jpg",
        recommend: [10,11,12,13]
      },
      "4": {
        name: "Toy Story 3",
        year: "2010",
        datePublished: "18 June 2010",
        country: "USA",
        length: 103,
        category: "Animation, Adventure, Comedy ",
        director: "Lee Unkrich",
        actors: "Tom Hanks, Tim Allen, Joan Cusack",
        description: "The toys are mistakenly delivered to a day-care center instead of the attic right before Andy leaves for college, and it's up to Woody to convince the other toys that they weren't abandoned and to return home.",
        image: "assets/images/all/5.jpg",
        recommend: [14,15,16,17]
      },
      "5": {
        name: "Inception",
        year: "2010",
        datePublished: "16 July 2010",
        country: "USA",
        length: 148,
        category: "Action, Mystery, Sci-Fi",
        director: "Christopher Nolan",
        actors: "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page",
        description: "A thief who steals corporate secrets through use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
        image: "assets/images/all/6.jpg",
        recommend: [2,18,19,20]
      },
      "6": {
        name: "True Grit",
        year: "2010",
        datePublished: "22 December 2010",
        country: "USA",
        length: 110,
        category: "Adventure, Drama, Western",
        director: "Ethan Coen, Joel Coen",
        actors: "Jeff Bridges, Matt Damon, Hailee Steinfeld",
        description: "A tough U.S. Marshal helps a stubborn teenager track down her father's murderer.",
        image: "assets/images/all/7.jpg",
        recommend: [21,22,23,24]
      },
      "7": {
        name: "How to Train Your Dragon",
        year: "2010",
        datePublished: "26 March 2010",
        country: "USA",
        length: 98,
        category: "Animation, Adventure, Family ",
        director: "Dean DeBlois, Chris Sanders",
        actors: "Jay Baruchel, Gerard Butler, Christopher Mintz-Plasse",
        description: "A hapless young Viking who aspires to hunt dragons becomes the unlikely friend of a young dragon himself, and learns there may be more to the creatures than he assumed.",
        image: "assets/images/all/8.jpg",
        recommend: [14,16,17,25]
      },
      "8": {
        name: "Looper",
        year: "2012",
        datePublished: "28 September 2012",
        country: "USA",
        length: 119,
        category: "Action, Crime, Sci-Fi ",
        director: "Rian Johnson",
        actors: "Joseph Gordon-Levitt, Bruce Willis, Emily Blunt",
        description: "In 2074, when the mob wants to get rid of someone, the target is sent into the past, where a hired gun awaits - someone like Joe - who one day learns the mob wants to 'close the loop' by sending back Joe's future self for assassination.",
        image: "assets/images/all/9.jpg",
        recommend: [26,27,28,29]
      },
      "9": {
        name: "Avatar",
        year: "2009",
        datePublished: "17 December 2009",
        country: "USA",
        length: 162,
        category: "Action, Adventure, Fantasy",
        director: "James Cameron",
        actors: "Sam Worthington, Zoe Saldana",
        description: "A Paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home",
        image: "assets/images/all/10.jpg",
        recommend: [30,31,32,33]
      },
      "10": {
        name: "Forrest Gump",
        year: "1994",
        datePublished: "6 July 1994",
        country: "USA",
        length: 142,
        category: "Drama, Romance",
        director: "Robert Zemeckis",
        actors: "Tom Hanks, Robin Wright, Gary Sinise",
        description: "Forrest Gump, while not intelligent, has accidentally been present at many historic moments, but his true love, Jenny Curran, eludes him.",
        image: "assets/images/all/11.jpg",
        recommend: [2,3,34,35]
      },
      "11": {
        name: "Frozen",
        year: "2013",
        datePublished: "28 November 2013",
        country: "USA",
        length: 102,
        category: "Animation, Adventure, Comedy",
        director: "Chris Buck, Jennifer Lee",
        actors: "Kristen Bell, Idina Menzel, Jonathan Groff",
        description: "When the newly crowned Queen Elsa accidentally uses her power to turn things into ice to curse her home in infinite winter, her sister, Anna, teams up with a mountain man, his playful reindeer, and a snowman to change the weather condition.",
        image: "assets/images/all/12.jpg",
        recommend: [36,37,38,16]
      },
      "12": {
        name: "Gladiator",
        year: "2000",
        datePublished: "18 May 2000",
        country: "USA",
        length: 155,
        category: "Action, Drama",
        director: "Ridley Scott",
        actors: "Russell Crowe, Joaquin Phoenix, Connie Nielsen",
        description: "When a Roman general is betrayed and his family murdered by an emperor's corrupt son, he comes to Rome as a gladiator to seek revenge.",
        image: "assets/images/all/13.jpg",
        recommend: [39,40,35,19]
      },
      "13": {
        name: "Braveheart",
        year: "1995",
        datePublished: "24 May 1995",
        country: "USA",
        length: 177,
        category: "Action, Biography, Drama",
        director: "Mel Gibson",
        actors: "Mel Gibson, Sophie Marceau, Patrick McGoohan",
        description: "When his secret bride is executed for assaulting an English soldier who tried to rape her, William Wallace begins a revolt and leads Scottish warriors against the cruel English tyrant who rules Scotland with an iron fist.",
        image: "assets/images/all/14.jpg",
        recommend: [42,43,40,41]
      },
      "14": {
        name: "Titanic",
        year: "1997",
        datePublished: "9 January 1998",
        country: "USA",
        length: 194,
        category: "Drama,Romance",
        director: "James Cameron",
        actors: "Leonardo DiCaprio, Kate Winslet, Billy Zane",
        description: "A seventeen-year-old aristocrat falls in love with a kind, but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
        image: "assets/images/all/15.jpg",
        recommend: [9,31,44,45]
      },
      "15": {
        name: "The Lion King",
        year: "1994",
        datePublished: "24 June 1994",
        country: "USA",
        length: 89,
        category: "Animation, Adventure, Drama",
        director: "Roger Allers, Rob Minkoff",
        actors: "Matthew Broderick, Jeremy Irons, James Earl Jones",
        description: "Tricked into thinking that he caused the death of his father, a lion cub flees and abandons his destiny as the future king.",
        image: "assets/images/all/16.jpg",
        recommend: [25,17,16,14]
      },
      "16": {
        name: "Pulp Fiction",
        year: "1994",
        datePublished: "",
        country: "USA",
        length: 154,
        category: "Crime, Drama",
        director: "Quentin Tarantino",
        actors: "John Travolta, Uma Thurman, Samuel L. Jackson",
        description: "The lives of two mob hit men, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
        image: "assets/images/all/17.jpg",
        recommend: [2,19,46,47]
      },
      "17": {
        name: "Silver Linings Playbook",
        year: "2012",
        datePublished: "25 December 2012",
        country: "USA",
        length: 122,
        category: "Comedy, Drama, Romance",
        director: "David O. Russell",
        actors: "Bradley Cooper, Jennifer Lawrence, Robert De Niro",
        description: "After a stint in a mental institution, former teacher Pat Solitano moves back in with his parents and tries to reconcile with his ex-wife. Things get more challenging when Pat meets Tiffany, a mysterious girl with problems of her own.",
        image: "assets/images/all/18.jpg",
        recommend: [48,4,49,50]
      },
      "18": {
        name: "The Dark Knight",
        year: "2008",
        datePublished: "24 July 2008",
        country: "USA, UK",
        length: 152,
        category: "Action, Crime, Drama",
        director: "Christopher Nolan",
        actors: "Christian Bale, Heath Ledger, Aaron Eckhart",
        description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, the caped crusader must come to terms with one of the greatest psychological tests of his ability to fight injustice.",
        image: "assets/images/all/19.jpg",
        recommend: [20,3,35,51]
      },
      "19": {
        name: "The Matrix",
        year: "1999",
        datePublished: "24 June 1999",
        country: "USA, Australia",
        length: 136,
        category: "Action, Sci-Fi",
        director: "Andy Wachowski",
        actors: " Keanu Reeves, Laurence Fishburne, Carrie-Anne ",
        description: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
        image: "assets/images/all/20.jpg",
        recommend: [51,3,2,47]
      },
      "20": {
        name: "The Twilight Saga: Breaking Dawn - Part 2",
        year: "2012",
        datePublished: "15 November 2012",
        country: "USA",
        length: 115,
        category: "Adventure, Drama, Fantasy",
        director: "Bill Condon",
        actors: "Kristen Stewart, Robert Pattinson, Taylor Lautner",
        description: "After the birth of Renesmee, the Cullens gather other vampire clans in order to protect the child from a false allegation that puts the family in front of the Volturi.",
        image: "assets/images/all/21.jpg",
        recommend: [52,53,54,55]
      },
      "21": {
        name: "10 things i hate about you",
        year: "1999",
        datePublished: "1 July 1999",
        country: "USA",
        length: 97,
        category: "Comedy, Drama, Romance",
        director: "Gil Junger",
        actors: "Heath Ledger, Julia Stiles, Joseph Gordon-Levitt",
        description: "A new kid must find a guy to date the meanest girl in school, the older sister of the girl he has a crush on, who cannot date until her older sister does.",
        image: "assets/images/all/22.jpg",
        recommend: [56,57,58,59]
      },
      "22": {
        name: "Despicable Me 2",
        year: "2013",
        datePublished: "4 July 2013",
        country: "USA",
        length: 98,
        category: "Animation, Comedy, Family",
        director: "Pierre Coffin, Chris Renaud",
        actors: " Steve Carell, Kristen Wiig, Benjamin Bratt",
        description: "When Gru, the world's most super-bad turned super-dad has been recruited by a team of officials to stop lethal muscle and a host of Gru's own, He has to fight back with new gadgetry, cars, and more minion madness.",
        image: "assets/images/all/23.jpg",
        recommend: [16,38,60,37]
      },
      "23": {
        name: "Finding Nemo",
        year: "2003",
        datePublished: "30 May 2003",
        country: "USA",
        length: 100,
        category: "Animation, Adventure, Comedy",
        director: "Andrew Stanton, Lee Unkrich",
        actors: "Albert Brooks, Ellen DeGeneres, Alexander Gould",
        description: "After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.",
        image: "assets/images/all/24.jpg",
        recommend: [16,25,14,15]
      },
      "24": {
        name: "The Sixth Sense",
        year: "1999",
        datePublished: "7 October 1999",
        country: "USA",
        length: 107,
        category: "Drama, Mystery, Thriller",
        director: "M. Night Shyamalan",
        actors: "Bruce Willis, Haley Joel Osment, Toni Collette",
        description: "A boy who communicates with spirits that don't know they're dead seeks the help of a disheartened child psychologist.",
        image: "assets/images/all/25.jpg",
        recommend: [61,40,43,46]
      }
    };

    this.recommendations = {
      "0": {
        name: "Inglourious Basterds",
        year: "2009",
        datePublished: "21 August 2009",
        country: "USA",
        length: 153,
        category: "Adventure, Drama, War ",
        director: "Quentin Tarantino, Eli Roth (uncredited)",
        actors: "Brad Pitt, Diane Kruger, Eli Roth",
        description: "In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans for the same.",
        image: "assets/images/rec/MV5BMjIzMDI4MTUzOV5BMl5BanBnXkFtZTcwNDY3NjA3Mg@@._V1_SY317_CR0,0,214,317_AL_.jpg"
      },
      "1": {
        name: "The Wolf of Wall Street",
        year: "2013",
        datePublished: "25 December 2013",
        country: "USA",
        length: 180,
        category: "Biography, Comedy, Crime",
        director: "Martin Scorsese",
        actors: "Leonardo DiCaprio, Jonah Hill, Margot Robbie",
        description: "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.",
        image: "assets/images/rec/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_SX214_AL_.jpg"
      },
      "2": {
        name: "Fight Club",
        year: "1999",
        datePublished: "15 October 1999",
        country: "USA",
        length: 139,
        category: "Biography, Comedy, Crime",
        director: "David Fincher",
        actors: "Brad Pitt, Edward Norton, Helena Bonham Carter",
        description: "An insomniac office worker looking for a way to change his life crosses paths with a devil-may-care soap maker and they form an underground fight club that evolves into something much, much more...",
        image: "assets/images/rec/MV5BMjIwNTYzMzE1M15BMl5BanBnXkFtZTcwOTE5Mzg3OA@@._V1_SX214_AL_.jpg"
      },
      "3": {
        name: "Inception",
        year: "2010",
        datePublished: "16 July 2010",
        country: "USA",
        length: 148,
        category: "Action, Mystery, Sci-Fi",
        director: "Christopher Nolan",
        actors: "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page",
        description: "A thief who steals corporate secrets through use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
        image: "assets/images/rec/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX214_AL_.jpg"
      },
      "4": {
        name: "Life of Pi",
        year: "2012",
        datePublished: "21 November 2012",
        country: "USA",
        length: 127,
        category: "Adventure, Drama",
        director: "Ang Lee",
        actors: "Suraj Sharma, Irrfan Khan, Adil Hussain",
        description: "A young man who survives a disaster at sea is hurtled into an epic journey of adventure and discovery. While cast away, he forms an unexpected connection with another survivor: a fearsome Bengal tiger.",
        image: "assets/images/rec/MV5BNTg2OTY2ODg5OF5BMl5BanBnXkFtZTcwODM5MTYxOA@@._V1_SX214_AL_.jpg"
      },
      "5": {
        name: "The Social Network",
        year: "2010",
        datePublished: "1 October 2010",
        country: "USA",
        length: 120,
        category: "Biography, Drama",
        director: "David Fincher",
        actors: "Jesse Eisenberg, Andrew Garfield, Justin Timberlake",
        description: "Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, but is later sued by two brothers who claimed he stole their idea, and the cofounder who was later squeezed out of the business.",
        image: "assets/images/rec/MV5BMTM2ODk0NDAwMF5BMl5BanBnXkFtZTcwNTM1MDc2Mw@@._V1_SX214_AL_.jpg"
      },
      "6": {
        name: "Argo",
        year: "2012",
        datePublished: "12 October 2012",
        country: "USA",
        length: 120,
        category: "Drama, History, Thriller",
        director: "Ben Affleck",
        actors: "Ben Affleck, Bryan Cranston, John Goodman",
        description: "Acting under the cover of a Hollywood producer scouting a location for a science fiction film, a CIA agent launches a dangerous operation to rescue six Americans in Tehran during the U.S. hostage crisis in Iran in 1980.",
        image: "assets/images/rec/MV5BMTc3MjI0MjM0NF5BMl5BanBnXkFtZTcwMTYxMTQ1OA@@._V1_SY317_CR0,0,214,317_AL_.jpg"
      },
      "7": {
        name: "Dallas Buyers Club",
        year: "2013",
        datePublished: "22 November 2013",
        country: "USA",
        length: 117,
        category: "Biography, Drama",
        director: "Jean-Marc VallÃ©e",
        actors: "Matthew McConaughey, Jennifer Garner, Jared Leto",
        description: "In 1985 Dallas, electrician and hustler Ron Woodroof works around the system to help AIDS patients get the medication they need after he is himself diagnosed with the disease.",
        image: "assets/images/anBnXkFtZTgwMjEyMjE0MDE@._V1_SX214_AL_.jpg"
      },
      "8": {
        name: "Silver Linings Playbook",
        year: "2012",
        datePublished: "25 December 2012",
        country: "USA",
        length: 122,
        category: "Comedy, Drama, Romance",
        director: "David O. Russell",
        actors: "Bradley Cooper, Jennifer Lawrence, Robert De Niro",
        description: "After a stint in a mental institution, former teacher Pat Solitano moves back in with his parents and tries to reconcile with his ex-wife. Things get more challenging when Pat meets Tiffany, a mysterious girl with problems of her own.",
        image: "assets/images/rec/MV5BMTM2MTI5NzA3MF5BMl5BanBnXkFtZTcwODExNTc0OA@@._V1_SX214_AL_.jpg"
      },
      "9": {
        name: "The Curious Case of Benjamin Button",
        year: "2008",
        datePublished: "25 December 2008",
        country: "USA",
        length: 166,
        category: "Drama, Fantasy, Romance",
        director: "David Fincher",
        actors: "Brad Pitt, Cate Blanchett, Tilda Swinton",
        description: "Tells the story of Benjamin Button, a man who starts aging backwards with bizarre consequences.",
        image: "assets/images/rec/MV5BNjQ0NTY2ODY2M15BMl5BanBnXkFtZTgwMjE4MzkxMDE@._V1_SY317_CR0,0,214,317_AL_.jpg"
      },
      "10": {
        name: "Avengers: Age of Ultron",
        year: "2015",
        datePublished: "1 May 2015",
        country: "USA",
        length: 141,
        category: "Action, Adventure, Sci-Fi",
        director: "Joss Whedon",
        actors: "Robert Downey Jr., Chris Evans, Mark Ruffalo",
        description: "When Tony Stark and Bruce Banner try to jump-start a dormant peacekeeping program called Ultron, things go horribly wrong and it's up to Earth's Mightiest Heroes to stop the villainous Ultron from enacting his terrible plans.",
        image: "assets/images/rec/MV5BMTU4MDU3NDQ5Ml5BMl5BanBnXkFtZTgwOTU5MDUxNTE@._V1_SY317_CR1,0,214,317_AL_.jpg"
      },
      "11": {
        name: "Mad Max Beyond Thunderdome",
        year: "1985",
        datePublished: "10 July 1985",
        country: "USA",
        length: 107,
        category: "Action, Adventure, Sci-Fi ",
        director: "George Miller, George Ogilvie",
        actors: "Mel Gibson, Tina Turner, Bruce Spence",
        description: "A former Australian policeman is rescued by a tribe of children when he is banished from a desert town and sent into the desert to die by the desert town's evil queen.",
        image: "assets/images/rec/MV5BMTk0MDQ5NTYxNV5BMl5BanBnXkFtZTcwNTA0ODYyMQ@@._V1_SY317_CR11,0,214,317_AL_.jpg"
      },
      "12": {
        name: "Mad Max",
        year: "1979",
        datePublished: "12 April 1979",
        country: "Australia",
        length: 88,
        category: "Action, Adventure, Sci-Fi ",
        director: "George Miller",
        actors: "Mel Gibson, Joanne Samuel, Hugh Keays-Byrne",
        description: "In a self-destructing world, a vengeful Australian policeman sets out to stop a violent motorcycle gang.",
        image: "assets/images/rec/MV5BMTM4Mjg5ODEzMV5BMl5BanBnXkFtZTcwMDc3NDk0NA@@._V1_SX214_AL_.jpg"
      },
      "13": {
        name: "Tomorrowland",
        year: "2015",
        datePublished: "22 May 2015",
        country: "USA",
        length: 130,
        category: "Action, Adventure, Mystery ",
        director: "Brad Bird",
        actors: "George Clooney, Britt Robertson, Hugh Laurie",
        description: "Bound by a shared destiny, a teen bursting with scientific curiosity and a former boy-genius inventor embark on a mission to unearth the secrets of a place somewhere in time and space that exists in their collective memory.",
        image: "assets/images/rec/MV5BMTQ4OTgzNTkwNF5BMl5BanBnXkFtZTgwMzI3MDE3NDE@._V1_SX214_AL_.jpg"
      },
      "14": {
        name: "Up",
        year: "2009",
        datePublished: "29 May 2009",
        country: "USA",
        length: 96,
        category: "Animation, Adventure, Comedy",
        director: "Pete Docter, Bob Peterson",
        actors: "Edward Asner, Jordan Nagai, John Ratzenberger",
        description: "To avoid being taken away to a nursing home, an old widower tries to fly his home to Paradise Falls, South America, along with a boy scout who accidentally lifted off with him.",
        image: "assets/images/rec/MV5BMTk3NDE2NzI4NF5BMl5BanBnXkFtZTgwNzE1MzEyMTE@._V1_SX214_AL_.jpg"
      },
      "15": {
        name: "The Lion King",
        year: "1994",
        datePublished: "24 June 1994",
        country: "USA",
        length: 89,
        category: "Animation, Adventure, Drama",
        director: "Roger Allers, Rob Minkoff",
        actors: "Matthew Broderick, Jeremy Irons, James Earl Jones",
        description: "Tricked into thinking that he caused the death of his father, a lion cub flees and abandons his destiny as the future king.",
        image: "assets/images/rec/MV5BMjEyMzgwNTUzMl5BMl5BanBnXkFtZTcwNTMxMzM3Ng@@._V1_SY317_CR15,0,214,317_AL_.jpg"
      },
      "16": {
        name: "Monsters, Inc.",
        year: "2001",
        datePublished: "2 November 2001",
        country: "USA",
        length: 92,
        category: "Animation, Adventure, Comedy ",
        director: "Pete Docter, David Silverman",
        actors: "Billy Crystal, John Goodman, Mary Gibbs",
        description: "Monsters generate their city's power by scaring children, but they are terribly afraid themselves of being contaminated by children, so when one enters Monstropolis, top scarer Sulley finds his world disrupted.",
        image: "assets/images/rec/MV5BMTY1NTI0ODUyOF5BMl5BanBnXkFtZTgwNTEyNjQ0MDE@._V1_SX214_AL_.jpg"
      },
      "17": {
        name: "Finding Nemo",
        year: "2003",
        datePublished: "30 May 2003",
        country: "USA",
        length: 100,
        category: "Animation, Adventure, Comedy",
        director: "Andrew Stanton, Lee Unkrich",
        actors: "Albert Brooks, Ellen DeGeneres, Alexander Gould",
        description: "After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.",
        image: "assets/images/rec/MV5BMTY1MTg1NDAxOV5BMl5BanBnXkFtZTcwMjg1MDI5Nw@@._V1_SY317_CR0,0,214,317_AL_.jpg"
      },
      "18": {
        name: "Django Unchained",
        year: "2012",
        datePublished: "25 December 2012",
        country: "USA",
        length: 165,
        category: "Western",
        director: "Quentin Tarantino",
        actors: "Jamie Foxx, Christoph Waltz, Leonardo DiCaprio",
        description: "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.",
        image: "assets/images/rec/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_SX214_AL_.jpg"
      },
      "19": {
        name: "Forrest Gump",
        year: "1994",
        datePublished: "6 July 1994",
        country: "USA",
        length: 142,
        category: "Drama, Romance",
        director: "Robert Zemeckis",
        actors: "Tom Hanks, Robin Wright, Gary Sinise",
        description: "Forrest Gump, while not intelligent, has accidentally been present at many historic moments, but his true love, Jenny Curran, eludes him.",
        image: "assets/images/rec/MV5BMTQwMTA5MzI1MF5BMl5BanBnXkFtZTcwMzY5Mzg3OA@@._V1_SX214_AL_.jpg"
      },
      "20": {
        name: "The Dark Knight Rises",
        year: "2012",
        datePublished: "20 July 2012",
        country: "USA",
        length: 165,
        category: "Action, Thriller",
        director: "Christopher Nolan",
        actors: "Christian Bale, Tom Hardy, Anne Hathaway",
        description: "Eight years after the Joker's reign of anarchy, the Dark Knight is forced to return from his imposed exile to save Gotham City from the brutal guerrilla terrorist Bane with the help of the enigmatic Catwoman.",
        image: "assets/images/rec/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_SX214_AL_.jpg"
      },
      "21": {
        name: "Burn After Reading",
        year: "2008",
        datePublished: "12 September 2008",
        country: "USA",
        length: 96,
        category: "Comedy, Crime, Drama",
        director: "Ethan Coen, Joel Coen",
        actors: "Brad Pitt, Frances McDormand, George Clooney",
        description: "A disk containing the memoirs of a CIA agent ends up in the hands of two unscrupulous gym employees who attempt to sell it.",
        image: "assets/images/rec/MV5BMTczNjQxODE0N15BMl5BanBnXkFtZTcwMzIxMjc3MQ@@._V1_SX214_AL_.jpg"
      },
      "22": {
        name: "O Brother, Where Art Thou?",
        year: "2000",
        datePublished: "2 February 2001",
        country: "USA",
        length: 106,
        category: "Adventure, Comedy, Crime ",
        director: "Joel Coen, Ethan Coen (uncredited)",
        actors: "George Clooney, John Turturro, Tim Blake Nelson",
        description: "In the deep south during the 1930s, three escaped convicts search for hidden treasure while a relentless lawman pursues them.",
        image: "assets/images/rec/MV5BMTI3MTEwMTAzMF5BMl5BanBnXkFtZTYwMTMxNTI5._V1_SY317_CR5,0,214,317_AL_.jpg"
      },
      "23": {
        name: "Miller's Crossing",
        year: "1990",
        datePublished: "5 October 1990",
        country: "USA",
        length: 115,
        category: "Crime, Drama, Thriller",
        director: "Joel Coen, Ethan Coen (uncredited)",
        actors: "Gabriel Byrne, Albert Finney, John Turturro",
        description: "Tom Regan, an advisor to a Prohibition-era crime boss, tries to keep the peace between warring mobs but gets caught in divided loyalties.",
        image: "assets/images/rec/MV5BMTk2NDIxNzEyNF5BMl5BanBnXkFtZTYwMjk2NTk5._V1_SY317_CR5,0,214,317_AL_.jpg"
      },
      "24": {
        name: "A Serious Man",
        year: "2009",
        datePublished: "6 November 2009",
        country: "USA",
        length: 106,
        category: "Comedy, Drama ",
        director: "Ethan Coen, Joel Coen",
        actors: "Michael Stuhlbarg, Richard Kind, Sari Lennick",
        description: "Larry Gopnik, a Midwestern physics teacher, watches his life unravel over multiple sudden incidents. Though seeking meaning and answers amidst his turmoils, he seems to keep sinking.",
        image: "assets/images/rec/MV5BMjAwODUxMjA0M15BMl5BanBnXkFtZTcwNjIyMzY3Mg@@._V1_SX214_AL_.jpg"
      },
      "25": {
        name: "Toy Story 3",
        year: "2010",
        datePublished: "18 June 2010",
        country: "USA",
        length: 103,
        category: "Animation, Adventure, Comedy ",
        director: "Lee Unkrich",
        actors: "Tom Hanks, Tim Allen, Joan Cusack",
        description: "The toys are mistakenly delivered to a day-care center instead of the attic right before Andy leaves for college, and it's up to Woody to convince the other toys that they weren't abandoned and to return home.",
        image: "assets/images/rec/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SY317_CR5,0,214,317_AL_.jpg"
      },
      "26": {
        name: "Oblivion",
        year: "2013",
        datePublished: "19 April 2013",
        country: "USA",
        length: 124,
        category: "Action, Adventure, Mystery ",
        director: "Joseph Kosinski",
        actors: "Tom Cruise, Morgan Freeman, Andrea Riseborough",
        description: "A veteran assigned to extract Earth's remaining resources begins to question what he knows about his mission and himself.",
        image: "assets/images/rec/MV5BMTQwMDY0MTA4MF5BMl5BanBnXkFtZTcwNzI3MDgxOQ@@._V1_SX214_AL_.jpg"
      },
      "27": {
        name: "World War Z",
        year: "2013",
        datePublished: "21 June 2013",
        country: "USA",
        length: 116,
        category: "Action, Adventure, Horror",
        director: "Marc Forster",
        actors: "Brad Pitt, Mireille Enos, Daniella Kertesz",
        description: "United Nations employee Gerry Lane traverses the world in a race against time to stop the Zombie pandemic that is toppling armies and governments, and threatening to destroy humanity itself.",
        image: "assets/images/rec/MV5BMTg0NTgxMjIxOF5BMl5BanBnXkFtZTcwMDM0MDY1OQ@@._V1_SX214_AL_.jpg"
      },
      "28": {
        name: "Elysium",
        year: "2013",
        datePublished: "9 August 2013",
        country: "USA",
        length: 109,
        category: "Action, Drama, Sci-Fi ",
        director: "Neill Blomkamp",
        actors: "Matt Damon, Jodie Foster, Sharlto Copley",
        description: "In the year 2154, the very wealthy live on a man-made space station while the rest of the population resides on a ruined Earth. A man takes on a mission that could bring equality to the polarized worlds.",
        image: "assets/images/rec/MV5BNDc2NjU0MTcwNV5BMl5BanBnXkFtZTcwMjg4MDg2OQ@@._V1_SX214_AL_.jpg"
      },
      "29": {
        name: "I Am Legend",
        year: "2007",
        datePublished: "14 December 2007",
        country: "USA",
        length: 101,
        category: "Drama, Sci-Fi, Thriller ",
        director: "Francis Lawrence",
        actors: "Will Smith, Alice Braga, Charlie Tahan",
        description: "Years after a plague kills most of humanity and transforms the rest into monsters, the sole survivor in New York City struggles valiantly to find a cure.",
        image: "assets/images/rec/MV5BMTU4NzMyNDk1OV5BMl5BanBnXkFtZTcwOTEwMzU1MQ@@._V1_SY317_CR0,0,214,317_AL_.jpg"
      },
      "30": {
        name: "Titanic",
        year: "1997",
        datePublished: "9 January 1998",
        country: "USA",
        length: 194,
        category: "Drama,Romance",
        director: "James Cameron",
        actors: "Leonardo DiCaprio, Kate Winslet, Billy Zane",
        description: "A seventeen-year-old aristocrat falls in love with a kind, but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
        image: "assets/images/rec/MV5BMjExNzM0NDM0N15BMl5BanBnXkFtZTcwMzkxOTUwNw@@._V1_SY317_CR0,0,214,317_AL_.jpg"
      },
      "31": {
        name: "The Hunger Games",
        year: "2012",
        datePublished: "22 March 2012",
        country: "USA",
        length: 142,
        category: "Adventure, Sci-Fi",
        director: "Gary Ross",
        actors: "Jennifer Lawrence, Josh Hutcherson, Liam Hemsworth",
        description: "Katniss Everdeen voluntarily takes her younger sister's place in the Hunger Games, a televised fight to the death in which two teenagers from each of the twelve Districts of Panem are chosen at random to compete.",
        image: "assets/images/rec/MV5BMjA4NDg3NzYxMF5BMl5BanBnXkFtZTcwNTgyNzkyNw@@._V1_SX214_AL_.jpg"
      },
      "32": {
        name: "Iron Man",
        year: "2008",
        datePublished: "1 May 2008",
        country: "USA",
        length: 126,
        category: "Action, Adventure, Sci-Fi",
        director: "Jon Favreau",
        actors: "Robert Downey Jr., Gwyneth Paltrow, Terrence ",
        description: "After being held captive in an Afghan cave, an industrialist creates a unique weaponized suit of armor to fight evil.",
        image: "assets/images/rec/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_SX214_AL_.jpg"
      },
      "33": {
        name: "The Hobbit: An Unexpected Journey",
        year: "2012",
        datePublished: "13 December 2012",
        country: "USA, New Zealand",
        length: 169,
        category: "Adventure, Fantasy",
        director: "Peter Jackson",
        actors: "Martin Freeman, Ian McKellen, Richard Armitage",
        description: "A reluctant hobbit, Bilbo Baggins, sets out to the Lonely Mountain with a spirited group of dwarves to reclaim their mountain home - and the gold within it - from the dragon Smaug.",
        image: "assets/images/rec/MV5BMTcwNTE4MTUxMl5BMl5BanBnXkFtZTcwMDIyODM4OA@@._V1_SX214_AL_.jpg"
      },
      "34": {
        name: "Pulp Fiction",
        year: "1994",
        datePublished: "",
        country: "USA",
        length: 154,
        category: "Crime, Drama",
        director: "Quentin Tarantino",
        actors: "John Travolta, Uma Thurman, Samuel L. Jackson",
        description: "The lives of two mob hit men, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
        image: "assets/images/rec/MV5BMjE0ODk2NjczOV5BMl5BanBnXkFtZTYwNDQ0NDg4._V1_SY317_CR4,0,214,317_AL_.jpg"
      },
      "35": {
        name: "The Matrix",
        year: "1999",
        datePublished: "24 June 1999",
        country: "USA, Australia",
        length: 136,
        category: "Action, Sci-Fi",
        director: "Andy Wachowski",
        actors: " Keanu Reeves, Laurence Fishburne, Carrie-Anne ",
        description: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
        image: "assets/images/rec/MV5BMTkxNDYxOTA4M15BMl5BanBnXkFtZTgwNTk0NzQxMTE@._V1_SX214_AL_.jpg"
      },
      "36": {
        name: "Despicable Me 2",
        year: "2013",
        datePublished: "4 July 2013",
        country: "USA",
        length: 98,
        category: "Animation, Comedy, Family",
        director: "Pierre Coffin, Chris Renaud",
        actors: " Steve Carell, Kristen Wiig, Benjamin Bratt",
        description: "When Gru, the world's most super-bad turned super-dad has been recruited by a team of officials to stop lethal muscle and a host of Gru's own, He has to fight back with new gadgetry, cars, and more minion madness.",
        image: "assets/images/rec/MV5BMjExNjAyNTcyMF5BMl5BanBnXkFtZTgwODQzMjQ3MDE@._V1_SY317_CR0,0,214,317_AL_.jpg"
      },
      "37": {
        name: "Brave",
        year: "2012",
        datePublished: "12 July 2012",
        country: "USA",
        length: 93,
        category: "Animation, Adventure, Comedy",
        director: " Mark Andrews, Brenda Chapman",
        actors: "Kelly Macdonald, Billy Connolly, Emma Thompson",
        description: "Determined to make her own path in life, Princess Merida defies a custom that brings chaos to her kingdom. Granted one wish, Merida must rely on her bravery and her archery skills to undo a beastly curse.",
        image: "assets/images/rec/MV5BMzgwODk3ODA1NF5BMl5BanBnXkFtZTcwNjU3NjQ0Nw@@._V1_SY317_CR0,0,214,317_AL_.jpg"
      },
      "38": {
        name: "Tangled ",
        year: "2010",
        datePublished: "25 November 2010",
        country: "USA",
        length: 100,
        category: "Animation, Comedy, Family",
        director: "Nathan Greno, Byron Howard",
        actors: "Mandy Moore, Zachary Levi, Donna Murphy",
        description: "The magically long-haired Rapunzel has spent her entire life in a tower, but now that a runaway thief has stumbled upon her, she is about to discover the world for the first time, and who she really is.",
        image: "assets/images/rec/MV5BMTAxNDYxMjg0MjNeQTJeQWpwZ15BbWU3MDcyNTk2OTM@._V1_SX214_AL_.jpg"
      },
      "39": {
        name: "Braveheart",
        year: "1995",
        datePublished: "24 May 1995",
        country: "USA",
        length: 177,
        category: "Action, Biography, Drama",
        director: "Mel Gibson",
        actors: "Mel Gibson, Sophie Marceau, Patrick McGoohan",
        description: "When his secret bride is executed for assaulting an English soldier who tried to rape her, William Wallace begins a revolt and leads Scottish warriors against the cruel English tyrant who rules Scotland with an iron fist.",
        image: "assets/images/rec/MV5BNjA4ODYxMDU3Nl5BMl5BanBnXkFtZTcwMzkzMTk3OA@@._V1_SX214_AL_.jpg"
      },
      "40": {
        name: "The Green Mile",
        year: "1999",
        datePublished: "24 February 2000",
        country: "USA",
        length: 189,
        category: "Crime, Drama, Fantasy",
        director: "Frank Darabont",
        actors: "Tom Hanks, Michael Clarke Duncan, David Morse",
        description: "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.",
        image: "assets/images/rec/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_SY317_CR0,0,214,317_AL_.jpg"
      },
      "41": {
        name: "Gladiator",
        year: "2000",
        datePublished: "18 May 2000",
        country: "USA",
        length: 155,
        category: "Action, Drama",
        director: "Ridley Scott",
        actors: "Russell Crowe, Joaquin Phoenix, Connie Nielsen",
        description: "When a Roman general is betrayed and his family murdered by an emperor's corrupt son, he comes to Rome as a gladiator to seek revenge.",
        image: "assets/images/rec/MV5BMTgwMzQzNTQ1Ml5BMl5BanBnXkFtZTgwMDY2NTYxMTE@._V1_SY317_CR0,0,214,317_AL_.jpg"
      },
      "42": {
        name: "Saving Private Ryan",
        year: "1998",
        datePublished: "15 October 1998",
        country: "USA",
        length: 169,
        category: "Action, Drama, War",
        director: "Steven Spielberg",
        actors: "Tom Hanks, Matt Damon, Tom Sizemore",
        description: "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.",
        image: "assets/images/rec/MV5BNjczODkxNTAxN15BMl5BanBnXkFtZTcwMTcwNjUxMw@@._V1_SY317_CR9,0,214,317_AL_.jpg"
      },
      "43": {
        name: "The Silence of the Lambs",
        year: "1991",
        datePublished: "26 April 1991",
        country: "USA",
        length: 118,
        category: "Thriller",
        director: "Jonathan Demme",
        actors: " Jodie Foster, Anthony Hopkins, Lawrence A. Bonney",
        description: "A young F.B.I. cadet must confide in an incarcerated and manipulative killer to receive his help on catching another serial killer who skins his victims.",
        image: "assets/images/rec/MV5BMTQ2NzkzMDI4OF5BMl5BanBnXkFtZTcwMDA0NzE1NA@@._V1_SX214_AL_.jpg"
      },
      "44": {
        name: "Slumdog Millionaire",
        year: "2008",
        datePublished: "22 January 2009",
        country: "USA, UK",
        length: 120,
        category: "Drama, Romance",
        director: "Danny Boyle, Loveleen Tandan",
        actors: "Dev Patel, Freida Pinto, Saurabh Shukla",
        description: 'A Mumbai teen, who grew up in the slums, becomes a contestant on the Indian version of "Who Wants To Be A Millionaire?" He is arrested under suspicion of cheating, and while being interrogated, events from his life history are shown which explain why he knows the answers.',
        image: "assets/images/rec/MV5BMTU2NTA5NzI0N15BMl5BanBnXkFtZTcwMjUxMjYxMg@@._V1_SY317_CR0,0,214,317_AL_.jpg"
      },
      "45": {
        name: "Avatar",
        year: "2009",
        datePublished: "17 December 2009",
        country: "USA",
        length: 162,
        category: "Action, Adventure, Fantasy",
        director: "James Cameron",
        actors: "Sam Worthington, Zoe Saldana",
        description: "A Paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home",
        image: "assets/images/rec/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_SY317_CR0,0,214,317_AL_.jpg"
      },
      "46": {
        name: "Se7en",
        year: "1995",
        datePublished: "22 September 1995",
        country: "USA",
        length: 127,
        category: "Drama, Mystery, Thriller",
        director: "David Fincher",
        actors: "Morgan Freeman, Brad Pitt, Kevin Spacey",
        description: "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his modus operandi.",
        image: "assets/images/rec/MV5BMTQwNTU3MTE4NF5BMl5BanBnXkFtZTcwOTgxNDM2Mg@@._V1_SX214_AL_.jpg"
      },
      "47": {
        name: "The Dark Knight",
        year: "2008",
        datePublished: "24 July 2008",
        country: "USA, UK",
        length: 152,
        category: "Action, Crime, Drama",
        director: "Christopher Nolan",
        actors: "Christian Bale, Heath Ledger, Aaron Eckhart",
        description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, the caped crusader must come to terms with one of the greatest psychological tests of his ability to fight injustice.",
        image: "assets/images/rec/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SY317_CR0,0,214,317_AL_.jpg"
      },
      "48": {
        name: "American Hustle",
        year: "2013",
        datePublished: "26 December 2013",
        country: "USA",
        length: 138,
        category: "Crime, Drama",
        director: "David O. Russell",
        actors: "Christian Bale, Amy Adams, Bradley Cooper",
        description: "A con man, Irving Rosenfeld, along with his seductive partner Sydney Prosser, is forced to work for a wild FBI agent, Richie DiMaso, who pushes them into a world of Jersey powerbrokers and mafia.",
        image: "assets/images/rec/MV5BNjkxMTc0MDc4N15BMl5BanBnXkFtZTgwODUyNTI1MDE@._V1_SX214_AL_.jpg"
      },
      "49": {
        name: "Black Swan",
        year: "2010",
        datePublished: "17 December",
        country: "USA",
        length: 108,
        category: "Drama, Mystery, Thriller",
        director: "Darren Aronofsky",
        actors: "Natalie Portman, Mila Kunis, Vincent Cassel",
        description: 'A ballet dancer wins the lead in "Swan Lake" and is perfect for the role of the delicate White Swan - Princess Odette - but slowly loses her mind as she becomes more and more like Odile, the Black Swan.',
        image: "assets/images/rec/MV5BNzY2NzI4OTE5MF5BMl5BanBnXkFtZTcwMjMyNDY4Mw@@._V1_SX214_AL_.jpg"
      },
      "50": {
        name: "The Perks of Being a Wallflower",
        year: "2012",
        datePublished: "18 October 2012",
        country: "USA",
        length: 102,
        category: "Drama, Romance",
        director: "Stephen Chbosky",
        actors: "Logan Lerman, Emma Watson, Ezra Miller",
        description: "An introvert freshman is taken under the wings of two seniors who welcome him to the real world.",
        image: "assets/images/rec/MV5BMzIxOTQyODU1OV5BMl5BanBnXkFtZTcwMDQ4Mjg4Nw@@._V1_SY317_CR0,0,214,317_AL_.jpg"
      },
      "51": {
        name: "The Lord of the Rings: The Return of the King",
        year: "2003",
        datePublished: "18 December 2003",
        country: "USA",
        length: 201,
        category: "Adventure, Fantasy",
        director: "Peter Jackson",
        actors: "Elijah Wood, Viggo Mortensen, Ian McKellen",
        description: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
        image: "assets/images/rec/MV5BMjE4MjA1NTAyMV5BMl5BanBnXkFtZTcwNzM1NDQyMQ@@._V1_SX214_AL_.jpg"
      },
      "52": {
        name: "The Twilight Saga: Breaking Dawn - Part 1",
        year: "2011",
        datePublished: "17 November 2011",
        country: "USA",
        length: 117,
        category: "Adventure, Drama, Fantasy",
        director: "Bill Condon",
        actors: "Kristen Stewart, Robert Pattinson, Taylor Lautner",
        description: "The Quileutes close in on expecting parents Edward and Bella, whose unborn child poses a threat to the Wolf Pack and the towns people of Forks.",
        image: "assets/images/rec/MV5BODgxNDE0OTAzOF5BMl5BanBnXkFtZTcwNzcwODE2Ng@@._V1_SX214_AL_.jpg"
      },
      "53": {
        name: "The Twilight Saga: Eclipse",
        year: "2010",
        datePublished: "30 June 2010",
        country: "USA",
        length: 124,
        category: "Adventure, Drama, Fantasy",
        director: "David Slade",
        actors: "Kristen Stewart, Robert Pattinson, Taylor Lautner",
        description: "As a string of mysterious killings grips Seattle, Bella, whose high school graduation is fast approaching, is forced to choose between her love for vampire Edward and her friendship with werewolf Jacob.",
        image: "assets/images/rec/MV5BNDMwNjAzNzYwOF5BMl5BanBnXkFtZTcwMDY5NzcyMw@@._V1_SY317_CR0,0,214,317_AL_.jpg"
      },
      "54": {
        name: "Snow White and the Huntsman",
        year: "2012",
        datePublished: "26 July 2012",
        country: "USA",
        length: 127,
        category: "Action, Drama, Fantasy",
        director: "Rupert Sanders",
        actors: " Kristen Stewart, Chris Hemsworth, Charlize Theron",
        description: "In a twist to the fairy tale, the Huntsman ordered to take Snow White into the woods to be killed winds up becoming her protector and mentor in a quest to vanquish the Evil Queen.",
        image: "assets/images/rec/MV5BMTQ1NDA0MTk5OV5BMl5BanBnXkFtZTcwMTM4NDMwNw@@._V1_SX214_AL_.jpg"
      },
      "55": {
        name: "Red Riding Hood",
        year: "2011",
        datePublished: "7 April 2011",
        country: "USA, Canada",
        length: 100,
        category: "Fantasy, Horror, Mystery",
        director: "Catherine Hardwicke",
        actors: "Amanda Seyfried, Lukas Haas, Gary Oldman",
        description: "Set in a medieval village that is haunted by a werewolf, a young girl falls for an orphaned woodcutter, much to her family's displeasure.",
        image: "assets/images/rec/MV5BMTc4NjYyMzQ5MV5BMl5BanBnXkFtZTcwNjE5Mjc3NA@@._V1_SY317_CR0,0,214,317_AL_.jpg"
      },
      "56": {
        name: "Clueless",
        year: "1995",
        datePublished: "15 December 1995",
        country: "USA",
        length: 97,
        category: "Comedy, Romance",
        director: "Amy Heckerling",
        actors: "Alicia Silverstone, Stacey Dash, Brittany Murphy",
        description: "A rich high school student tries to boost a new pupil's popularity, but reckons without affairs of the heart getting in the way.",
        image: "assets/images/rec/MV5BMTgxODIxODE2MF5BMl5BanBnXkFtZTgwOTA4NjQxMTE@._V1_SY317_CR0,0,214,317_AL_.jpg"
      },
      "57": {
        name: "She's the Man",
        year: "2006",
        datePublished: "30 March 2006",
        country: "USA",
        length: 105,
        category: "Comedy, Romance",
        director: "Andy Fickman",
        actors: "Amanda Bynes, Laura Ramsey, Channing Tatum",
        description: "When her brother decides to ditch for a couple weeks in London, Viola heads over to his elite boarding school, disguises herself as him, and proceeds to fall for one of her soccer teammates. Little does she realize she's not the only one with romantic troubles, as she, as he, gets in the middle of a series of intermingled love affairs.",
        image: "assets/images/rec/MV5BMjEyMzAzMDk1Ml5BMl5BanBnXkFtZTcwNjg0OTEzMQ@@._V1_SX214_AL_.jpg"
      },
      "58": {
        name: "Easy A",
        year: "2010",
        datePublished: "25 November 2010",
        country: "USA",
        length: 92,
        category: "Comedy, Romance",
        director: "Will Gluck",
        actors: "Emma Stone, Amanda Bynes, Penn Badgley",
        description: "A clean-cut high school student relies on the school's rumor mill to advance her social and financial standing.",
        image: "assets/images/rec/MV5BMjE1MzU1Mjg1OF5BMl5BanBnXkFtZTcwNDc3NDQ2Mw@@._V1_SY317_CR0,0,214,317_AL_.jpg"
      },
      "59": {
        name: "Mean Girls",
        year: "2004",
        datePublished: "24 June 2004",
        country: "USA",
        length: 97,
        category: "Comedy",
        director: "Mark Waters",
        actors: "Lindsay Lohan, Jonathan Bennett, Rachel McAdams",
        description: "Cady Heron is a hit with The Plastics, the A-list girl clique at her new school, until she makes the mistake of falling for Aaron Samuels, the ex-boyfriend of alpha Plastic Regina George.",
        image: "assets/images/rec/MV5BMjE1MDQ4MjI1OV5BMl5BanBnXkFtZTcwNzcwODAzMw@@._V1_SY317_CR5,0,214,317_AL_.jpg"
      },
      "60": {
        name: "Frozen",
        year: "2013",
        datePublished: "28 November 2013",
        country: "USA",
        length: 102,
        category: "Animation, Adventure, Comedy",
        director: "Chris Buck, Jennifer Lee",
        actors: "Kristen Bell, Idina Menzel, Jonathan Groff",
        description: "When the newly crowned Queen Elsa accidentally uses her power to turn things into ice to curse her home in infinite winter, her sister, Anna, teams up with a mountain man, his playful reindeer, and a snowman to change the weather condition.",
        image: "assets/images/rec/MV5BMTQ1MjQwMTE5OF5BMl5BanBnXkFtZTgwNjk3MTcyMDE@._V1_SX214_AL_.jpg"
      },
      "61": {
        name: "The Truman Show",
        year: "1998",
        datePublished: "30 October 1998",
        country: "USA",
        length: 103,
        category: "Drama",
        director: "Peter Weir",
        actors: "Jim Carrey, Ed Harris, Laura Linney",
        description: "An insurance salesman/adjuster discovers his entire life is actually a T.V. show.",
        image: "assets/images/rec/MV5BMTM4NjY2MTEzM15BMl5BanBnXkFtZTcwMTk2Njk3OA@@._V1_SX214_AL_.jpg"
      }
    };

    this.user = [];

    this.withImages = null;

    this.age = null;

    this.gender = null;

    this.alreadyDecided = false;

    this.completed = 0;
  });
