angular.module('recuserstudyApp').run(['$templateCache', function($templateCache) {
  'use strict';

  $templateCache.put('app/result/result.html',
    "<header class=hero-unit id=banner><div class=container><h1>Recommendation System User Study!</h1><br><h2>The Results</h2></div></header><div class=\"loading middle\" ng-if=loading><span class=\"glyphicon glyphicon-refresh glyphicon-refresh-animate\"></span></div><div class=container ng-show=!loading><div class=\"row text-center\"><h2>Total participants: {{stats.total}}</h2></div><div class=\"row results\"><div class=\"col-md-6 text-center\"><h3>Recommendations shown <b>with</b> images</h3><h4>Total participants: {{stats.withImages.total}}</h4><canvas id=pie1 class=\"chart chart-pie\" data=withImages labels=labels legend=true colours=colors></canvas></div><div class=\"col-md-6 text-center\"><h3>Recommendations shown <b>without</b> images</h3><h4>Total participants: {{stats.withoutImages.total}}</h4><canvas id=pie2 class=\"chart chart-pie\" data=withoutImages labels=labels legend=true colours=colors></canvas></div></div></div>"
  );


  $templateCache.put('app/step1/step1.html',
    "<div class=\"container step1\"><div class=\"row text-center\"><h3 ng-show=!userMovies.length>Please pick your favorite movies from the following list</h3><h3 ng-show=\"userMovies.length && userMovies.length < 10\">Please choose {{10 - userMovies.length}} more movies</h3><h3><button class=\"btn btn-primary btn-lg\" ng-show=\"userMovies.length === 10\" ui-sref=step2({recId:1})>Continue to next step&nbsp&nbsp<span class=\"glyphicon glyphicon glyphicon-ok\" aria-hidden=true></span></button></h3><br></div><div class=pick_movies><div class=row><div class=\"col-md-1 text-center\"><button type=button class=\"btn btn-default btn-lg menu_button\" ng-click=left() ng-disabled=!firstIndex><span class=\"glyphicon glyphicon-chevron-left\" aria-hidden=true></span></button></div><div class=\"col-sm-6 col-md-1 no_padding\" ng-repeat=\"movie in movies\" ng-click=addMovie($index)><div ng-class=calcMovie(movie)><img ng-src={{movie.image}} alt={{movie.name}} class=\"intro_image pointer\"><div class=caption><h5><b>{{movie.name}}</b></h5><span class=year>{{movie.year}}</span></div></div></div><div class=\"col-md-1 text-center\"><button type=button class=\"btn btn-default btn-lg menu_button\" ng-click=right() ng-disabled=\"lastIndex === totalMovies\"><span class=\"glyphicon glyphicon-chevron-right\" aria-hidden=true></span></button></div></div></div><br><br><div class=row ng-show=userMovies.length><h3 class=text-center>Your choice:</h3><br><div class=\"col-sm-6 col-md-1\"></div><div class=\"col-sm-6 col-md-1 no_padding\" ng-repeat=\"movie in userMovies\" ng-click=removeMovie($index)><div class=thumbnail><img ng-src={{movie.image}} alt={{movie.name}} class=\"intro_image pointer\"><div class=caption><h5><b>{{movie.name}}</b></h5><span class=year>{{movie.year}}</span></div></div></div><div class=\"col-sm-6 col-md-1\"></div></div></div>"
  );


  $templateCache.put('app/step2/step2.html',
    "<div class=\"container step2\"><div class=\"row text-center\"><button class=\"btn btn-default navigate\" ng-show=\"completed > 0\" ng-disabled=\"loading || !completed || id == 1\" ng-click=back()><span class=\"glyphicon glyphicon-arrow-left\" aria-hidden=true></span></button><h3 class=inline>Recommendation {{id}}/10</h3><button class=\"btn btn-default navigate\" ng-show=\"completed > 0\" ng-disabled=\"loading || id > completed || id == 10\" ng-click=next()><span class=\"glyphicon glyphicon-arrow-right\" aria-hidden=true></span></button><div class=progress><div class=\"progress-bar progress-bar-success progress-bar-striped\" role=progressbar aria-valuenow=40 aria-valuemin=0 aria-valuemax=100 ng-style=calcProgress()>Total progress&nbsp&nbsp{{completed}}/10</div></div><br><br></div><div class=loading ng-if=loading><span class=\"glyphicon glyphicon-refresh glyphicon-refresh-animate\"></span></div><h3 class=\"text-center finish\"><button class=\"btn btn-primary btn-lg\" ng-show=\"completed === 10 && !loading\" ng-click=finish()>Finish&nbsp&nbsp<span class=\"glyphicon glyphicon glyphicon-ok\" aria-hidden=true></span></button></h3><div ng-show=!loading><div ng-class=calcWell(rec) ng-repeat=\"rec in recommendations\"><div class=col-md-4 ng-show=withImages><img ng-src={{rec.image}} alt={{rec.name}} class=img-responsive></div><div class=col-md-8><div class=row><h3 class=inline>{{rec.name}}</h3>&nbsp&nbsp({{rec.year}})</div><div class=row><span>{{rec.length}}&nbspmin</span>&nbsp|&nbsp<span>{{rec.category}}</span>&nbsp|&nbsp<span>{{rec.datePublished}}&nbsp({{rec.country}})</span></div><div class=\"row divider\"></div><div class=\"row description\"><div class=col-md-10>{{rec.description}}</div></div><div class=row><b>Directory:</b><span>&nbsp{{rec.director}}</span></div><div class=row><b>Actors:</b><span>&nbsp{{rec.actors}}</span></div><div class=row><button class=\"btn btn-primary choose_me\" ng-click=continue(rec)>I would like to watch this movie&nbsp&nbsp<span class=\"glyphicon glyphicon-thumbs-up\" aria-hidden=true></span></button></div></div></div><br><br><br><div class=\"row text-center\"><button class=\"btn btn-success btn-lg\" ng-click=continue()>Nothing suits me&nbsp&nbsp<span class=\"glyphicon glyphicon-thumbs-down\" aria-hidden=true></span></button></div></div></div>"
  );


  $templateCache.put('components/modal/modal.html',
    "<div class=modal-header><h4 ng-if=modal.title ng-bind-html=modal.title class=modal-title></h4></div><div class=modal-body><p ng-if=modal.text ng-bind=modal.text></p><div ng-if=modal.html ng-bind-html=modal.html></div></div><div class=modal-footer><button ng-repeat=\"button in modal.buttons\" ng-class=button.classes ng-click=button.click($event) ng-bind=button.text class=btn></button></div>"
  );


  $templateCache.put('components/movies/movies.html',
    "<div class=modal-header><h4 ng-if=modal.title ng-bind=modal.title class=modal-title></h4></div><div class=modal-body><p ng-if=modal.text ng-bind=modal.text></p><div ng-if=modal.html ng-bind-html=modal.html></div></div><div class=modal-footer><button ng-repeat=\"button in modal.buttons\" ng-class=button.classes ng-click=button.click($event) ng-bind=button.text class=btn></button></div>"
  );

}]);
